services:
  postgres:
    container_name: postgres_2
    image: postgres
    environment:
      POSTGRES_USER: nttdata-mlca
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5090:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_2
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmq_2
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
#  eureka-server:
#    image: miguel04/eureka-server2:latest
#    container_name: eureka-server-2
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#  apigateway:
#    image: miguel04/apigateway2:latest
#    container_name: apigateway_2
#    ports:
#      - "8092:8092"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
  producto:
    image: miguel04/producto:latest
    container_name: producto
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - config-server
#      - eureka-server
  validarproducto:
    image: miguel04/validarproducto:latest
    container_name: validarproducto
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - config-server
#      - eureka-server
  config-server:
    image: miguel04/config-server2:latest
    container_name: config-server2
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: