server:
  port: 8092

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin_2:9411
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/v1/producto/**
        - id: cliente
          uri: lb://VALIDARPRODUCTO
          predicates:
            - Path=/api/v1/producto-check/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8761/eureka
    fetch-registry: true
    register-with-eureka: true