server:
  port: 8092

spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: producto
          uri: lb://producto
          predicates:
            - Path=/api/v1/producto/**
          filters:
            - AutorizacionFilter
        - id: validarproducto
          uri: lb://validarproducto
          predicates:
            - Path=/api/v1/producto-check/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
          uri: lb://autenticacion
          predicates:
            - Path=/api/v1/autenticacion/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false