server:
  port: 8093
spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://postgres:5432/autenticacion
    username: nttdata-mlca
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkin_2:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false
  instance:
    prefer-ip-address: true

jwt:
  secret: secret

admin-paths:
  paths:
    - uri: "/api/v1/producto"
      method: "POST"
    - uri: "/api/v1/producto"
      method: "PUT"
    - uri: "/api/v1/producto/{1}[1-9]+[0-9]*"
      method: "DELETE"
    - uri: "/api/v1/producto-check/{1}[1-9]+[0-9]*"
      method: "GET"