server:
  port: 8090
spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://postgres:5432/producto
    username: nttdata-mlca
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false