server:
  port: 8091
spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://postgres:5432/productocheck
    username: nttdata-mlca
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false