server:
  port: 8090
spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://postgres_2:5432/producto
    username: nttdata-mlca
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql
  zipkin:
    base-url: http://zipkin_2:9411
  rabbitmq:
    addresses: rabbitmq_2:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      validarproductoCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    retry-aspect-order: 2
    instances:
      validarproductoRetry:
        registerHealthIndicator: true
        maxRetryAttempts: 7
        waitDuration: 3s
